RadioUrl = [
"https://Qurango.net/radio/ahmed_altrabulsi",
"https://Qurango.net/radio/ahmad_khader_altarabulsi",
"https://Qurango.net/radio/ahmed_amer",
"https://Qurango.net/radio/ibrahim_aldosari",
"https://Qurango.net/radio/addokali_mohammad_alalim",
"https://Qurango.net/radio/alfateh_alzubair",
"https://Qurango.net/radio/jamaan_alosaimi",
"https://Qurango.net/radio/hatem_fareed_alwaer",
"https://Qurango.net/radio/khalid_almohana",
"https://Qurango.net/radio/tareq_abdulgani_daawob",
"https://Qurango.net/radio/adel_alkhalbany",
"https://Qurango.net/radio/abdulrahman_almajed",
"https://Qurango.net/radio/abdullah_alkandari",
"https://Qurango.net/radio/ali_jaber",
"https://Qurango.net/radio/ali_hajjaj_alsouasi",
"https://Qurango.net/radio/emad_hafez",
"https://Qurango.net/radio/omar_alqazabri",
"https://Qurango.net/radio/fares_abbad",
"https://Qurango.net/radio/maher_al_meaqli",
"https://Qurango.net/radio/maher_shakhashero",
"https://Qurango.net/radio/mohammed_ayyub",
"https://Qurango.net/radio/mohammad_altablaway",
"https://Qurango.net/radio/mohammed_allohaidan",
"https://Qurango.net/radio/mohammed_jibreel",
"https://Qurango.net/radio/mohammad_rashad_alshareef",
"https://Qurango.net/radio/mohammad_saleh_alim_shah",
"https://Qurango.net/radio/mohammed_siddiq_alminshawi",
"https://Qurango.net/radio/mohammed_siddiq_alminshawi_mojawwad",
"https://Qurango.net/radio/mohammad_alabdullah_albizi",
"https://Qurango.net/radio/mohammad_alabdullah_aldorai",
"https://Qurango.net/radio/mohammad_abdullkarem",
"https://Qurango.net/radio/mohammad_abdullkarem_alasbahani",
"https://Qurango.net/radio/mahmood_al_rifai",
"https://Qurango.net/radio/mahmood_alsheimy",
"https://Qurango.net/radio/mahmoud_khalil_alhussary",
"https://Qurango.net/radio/mahmoud_khalil_alhussary_mojawwad",
"https://Qurango.net/radio/mahmoud_khalil_alhussary_warsh",
"https://Qurango.net/radio/mahmoud_ali__albanna",
"https://Qurango.net/radio/mahmoud_ali__albanna_mojawwad",
"https://Qurango.net/radio/mishary_alafasi",
"https://Qurango.net/radio/mustafa_ismail",
"https://Qurango.net/radio/mustafa_allahoni",
"https://Qurango.net/radio/mustafa_raad_alazawy",
"https://Qurango.net/radio/moeedh_alharthi",
"https://Qurango.net/radio/muftah_alsaltany_aldori_an_abi_amr",
"https://Qurango.net/radio/muftah_alsaltany_aldorai",
"https://Qurango.net/radio/muftah_alsaltany",
"https://Qurango.net/radio/muftah_alsaltany_ibn_thakwan_an_ibn_amr",
"https://Qurango.net/radio/mousa_bilal",
"https://Qurango.net/radio/nasser_alqatami",
"https://Qurango.net/radio/nabil_al_rifay",
"https://Qurango.net/radio/neamah_alhassan",
"https://Qurango.net/radio/hani_arrifai",
"https://Qurango.net/radio/waleed_alnaehi",
"https://Qurango.net/radio/yasser_aldosari",
"https://Qurango.net/radio/yasser_alqurashi",
"https://Qurango.net/radio/yasser_almazroyee",
"https://Qurango.net/radio/yahya_hawwa",
"https://Qurango.net/radio/yousef_alshoaey",
"https://Qurango.net/radio/yousef_bin_noah_ahmad",
"https://Qurango.net/radio/tarateel",
"https://qurango.net/radio/sahabah",
"https://Qurango.net/radio/mix",
"https://qurango.net/radio/mukhtasartafsir",
"https://Qurango.net/radio/ahmad_deban",
"https://qurango.net/radio/athkar_sabah",
"https://qurango.net/radio/athkar_masa",
"https://qurango.net/radio/albaqarah",
"https://qurango.net/radio/tafseer",
"https://qurango.net/radio/salma",
"https://qurango.net/radio/sakeenah",
"https://Qurango.net/radio/ahmad_alhawashi",
"https://Qurango.net/radio/ahmad_alajmy",
"https://Qurango.net/radio/ahmad_shaheen",
"https://Qurango.net/radio/ahmad_saber",
"https://Qurango.net/radio/ahmad_nauina",
"https://Qurango.net/radio/akram_alalaqmi",
"https://Qurango.net/radio/ibrahim_alakdar",
"https://Qurango.net/radio/idrees_abkr",
"https://qurango.net/radio/roqiah",
"https://Qurango.net/radio/alzain_mohammad_ahmad",
"https://Qurango.net/radio/aloyoon_alkoshi",
"https://qurango.net/radio/fatwa",
"https://Qurango.net/radio/alqaria_yassen",
"https://qurango.net/radio/eid",
"https://Qurango.net/radio/tawfeeq_assayegh",
"https://Qurango.net/radio/jamal_shaker_abdullah",
"https://Qurango.net/radio/khalid_aljileel",
"https://Qurango.net/radio/khaled_alqahtani",
"https://Qurango.net/radio/khalid_abdulkafi",
"https://Qurango.net/radio/khalifa_altunaiji",
"https://Qurango.net/radio/zaki_daghistani",
"https://Qurango.net/radio/saad_alghamdi",
"https://Qurango.net/radio/saud_alshuraim",
"https://Qurango.net/radio/sahl_yassin",
"https://Qurango.net/radio/sayeed_ramadan",
"https://Qurango.net/radio/shaik_abu_bakr_al_shatri",
"https://Qurango.net/radio/shirazad_taher",
"https://Qurango.net/radio/saber_abdulhakm",
"https://Qurango.net/radio/salah_albudair",
"https://Qurango.net/radio/salah_alhashim",
"https://Qurango.net/radio/slaah_bukhatir",
"https://Qurango.net/radio/adel_ryyan",
"https://Qurango.net/radio/abdelbari_altoubayti",
"https://Qurango.net/radio/abdulbari_mohammad",
"https://Qurango.net/radio/abdulbasit_abdulsamad_mojawwad",
"https://Qurango.net/radio/abdulbasit_abdulsamad_warsh",
"https://Qurango.net/radio/abdulbasit_abdulsamad",
"https://Qurango.net/radio/abdulrahman_alsudaes",
"https://Qurango.net/radio/abdulrasheed_soufi_khalaf",
"https://Qurango.net/radio/abdulrasheed_soufi_assosi",
"https://Qurango.net/radio/abdul_aziz_alahmad",
"https://Qurango.net/radio/abdullah_alkhalaf",
"https://Qurango.net/radio/abdullah_almattrod",
"https://Qurango.net/radio/abdullah_almousa",
"https://Qurango.net/radio/abdullah_basfer",
"https://Qurango.net/radio/abdullah_khayyat",
"https://Qurango.net/radio/abdullah_aljohany",
"https://Qurango.net/radio/abdulmohsin_alharthy",
"https://Qurango.net/radio/abdulmohsin_alobaikan",
"https://Qurango.net/radio/abdulmohsen_alqasim",
"https://Qurango.net/radio/abdulhadi_kanakeri",
"https://Qurango.net/radio/abdulwadood_haneef",
"https://Qurango.net/radio/ali_alhuthaifi_qalon",
"https://Qurango.net/radio/ali_alhuthaifi",
"https://qurango.net/radio/ayyoub2",
"https://Qurango.net/radio/mohammed_osman_khan",
"https://Qurango.net/radio/nasser_almajed",
"https://Qurango.net/radio/hitham_aljadani",
"https://Qurango.net/radio/bandar_balilah",
"https://Qurango.net/radio/fi_zilal_alsiyra",
"https://Qurango.net/radio/alaikhtiarat_alfiqhayh_bin_baz",
"https://Qurango.net/radio/majed_alzamel",
"https://Qurango.net/radio/sneineh",
"https://Qurango.net/radio/qeniwa",
"https://Qurango.net/radio/nasser_alosfor",
]


import vlc
import random

x_input ='n'

x = random.randint(0, len(RadioUrl)-1)
url = RadioUrl[x]

p = vlc.MediaPlayer(url)
print(url)

p.audio_set_volume(50)
p.play()

while(1):
    x_input = input("N for next \nset volume(0:10) : " )
    p.audio_set_volume(10*int(x_input))
        
        


        

    
